# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Houston United Malayalee Soccer Club
shorttitle: Houston United MSC
tagline: 
email: houstonunitedmsc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "http://shajanjp.github.io/houstonunitedmsc" # the subpath of your site, e.g. /blog
url: "http://houstonunitedmsc.com" # the base hostname & protocol for your site

social:
  twitter: houstonunitedmsc
  facebook: houstonunitedmsc
  instagram: houstonunitedmsc
  gplus: houstonunitedmsc
  whatsapp: https://chat.whatsapp.com/BCgR1GJUmc11XIq4Mwm2Rr
# Build settings
markdown: kramdown